# 임베딩 모델 설정
model:
  name: "BAAI/bge-m3"
  device: "cuda"
  batch_size: 32
  max_length: 1024

# Content 기반 추천 기법
recommendation:
  method: "weighted_avg"  # 옵션: max_pooling, weighted_avg, attention
  use_mmr: False # MMR 기법 사용 여부
  top_k: 7 # 추천할 뉴스레터 개수
  mmr_lambda: 0.7 # 0~1 사이의 값을 가지며, 1에 가까울수록 사용자 취향과 유사한 뉴스레터 위주로만 추천됨. 보통 0.7을 사용

# 데이터 생성 설정
data_generation:
  num_dummy_users: 50 # 생성할 가상 유저 수
