from datetime import datetime
from typing import Dict, List, Optional, Protocol, Sequence, Set, Tuple

import numpy as np

from app.recsys.types import Item, NewsletterMeta


class RecsysRepository(Protocol):
    """요청 시점 추천이 읽는 모든 데이터 접근. SQL 구현은 sql_repository.py,
    단위 테스트는 메모리 fake를 쓴다. 시각 인자는 모두 tz-aware(UTC)다."""

    def last_click_id(self, user_id: int) -> Optional[int]: ...

    def long_term_and_categories(self, user_id: int) -> Tuple[Optional[np.ndarray], List[int]]: ...

    def short_term_vector(self, user_id: int, since: datetime, limit: int) -> Optional[np.ndarray]: ...

    def onboarding_vector(self, user_id: int) -> Optional[np.ndarray]: ...

    def category_centroid(self, category_ids: Sequence[int], since: datetime) -> Optional[np.ndarray]: ...

    def knn_ids(self, query: np.ndarray, since: datetime, k: int) -> List[int]: ...

    def recent_ids(self, n: int) -> List[int]: ...

    def window_meta(self, since: datetime) -> List[NewsletterMeta]: ...

    def category_recent_ids(self, category_ids: Sequence[int], since: datetime, n: int) -> List[int]: ...

    def clicked_among(self, user_id: int, news_letter_ids: Sequence[int]) -> Set[int]: ...

    def items(self, news_letter_ids: Sequence[int]) -> Dict[int, Item]: ...

    def latest_batch(self, user_id: int) -> Optional[Tuple[datetime, List[int]]]: ...
