"""update news models schema

Revision ID: 69d38bb6753b
Revises: 78742dce5010
Create Date: 2026-01-23 20:52:54.630081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d38bb6753b'
down_revision: Union[str, Sequence[str], None] = '78742dce5010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_raw', 'press_category')
    op.drop_column('news_raw', 'writer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_raw', sa.Column('writer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('news_raw', sa.Column('press_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
