"""init tables

Revision ID: 78742dce5010
Revises: 
Create Date: 2026-01-23 18:20:52.806365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '78742dce5010'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_code', sa.Integer(), nullable=False, comment='100:Politics, 200:Economy...'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('news_letter',
    sa.Column('news_letter_id', sa.Integer(), nullable=False),
    sa.Column('news_letter_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('news_letter_sentence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('news_letter_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('news_letter_created_at', sa.DateTime(), nullable=False),
    sa.Column('news_letter_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('news_letter_keywords', sa.JSON(), nullable=True),
    sa.Column('raw_news_count', sa.Integer(), nullable=False),
    sa.Column('raw_news_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('news_letter_id')
    )
    op.create_table('news_letters_category',
    sa.Column('news_letter_batch_id', sa.Integer(), nullable=False),
    sa.Column('news_letter_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('news_letter_batch_id')
    )
    op.create_table('press',
    sa.Column('press_id', sa.Integer(), nullable=False),
    sa.Column('press_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('press_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_created_at', sa.DateTime(), nullable=False),
    sa.Column('user_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('user_gender_code', sa.Integer(), nullable=True, comment='0:unknown, 1:male, 2:female'),
    sa.Column('user_birth_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_email'), 'user', ['user_email'], unique=True)
    op.create_table('news_letter_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_letter_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['news_letter_id'], ['news_letter.news_letter_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_letter_today_batch',
    sa.Column('news_letter_batch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_letter_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('news_letter_batch_id')
    )
    op.create_table('news_raw',
    sa.Column('raw_news_id', sa.Integer(), nullable=False),
    sa.Column('press_id', sa.Integer(), nullable=False),
    sa.Column('raw_news_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_news_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('writer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_news_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_result', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('press_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_news_created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_news_crawled_at', sa.DateTime(), nullable=False),
    sa.Column('used_check', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['press_id'], ['press.press_id'], ),
    sa.PrimaryKeyConstraint('raw_news_id')
    )
    op.create_table('rss_uri',
    sa.Column('rss_raw_id', sa.Integer(), nullable=False),
    sa.Column('press_id', sa.Integer(), nullable=False),
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['press_id'], ['press.press_id'], ),
    sa.PrimaryKeyConstraint('rss_raw_id')
    )
    op.create_table('user_preferred_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferred_newsletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_letter_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_letter_id'], ['news_letter.news_letter_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferred_newsletter')
    op.drop_table('user_preferred_categories')
    op.drop_table('rss_uri')
    op.drop_table('news_raw')
    op.drop_table('news_letter_today_batch')
    op.drop_table('news_letter_categories')
    op.drop_index(op.f('ix_user_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('press')
    op.drop_table('news_letters_category')
    op.drop_table('news_letter')
    op.drop_table('category')
    # ### end Alembic commands ###
