"""Rename UserNewsLetterCTRLog table to lowercase

Revision ID: c97fb5709513
Revises: cd20ac487bae
Create Date: 2026-01-29 17:58:08.416815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c97fb5709513'
down_revision: Union[str, Sequence[str], None] = 'cd20ac487bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_newsletter_ctr_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('news_letter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_letter_id'], ['news_letter.news_letter_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.drop_table('User_NewsLetter_CTR_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_NewsLetter_CTR_log',
    sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('news_letter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['news_letter_id'], ['news_letter.news_letter_id'], name=op.f('User_NewsLetter_CTR_log_news_letter_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('User_NewsLetter_CTR_log_user_id_fkey')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('User_NewsLetter_CTR_log_pkey'))
    )
    op.drop_table('user_newsletter_ctr_log')
    # ### end Alembic commands ###
