"""update news schema based on latest ERD

Revision ID: ea199640471b
Revises: 69d38bb6753b
Create Date: 2026-01-23 21:42:07.849720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea199640471b'
down_revision: Union[str, Sequence[str], None] = '69d38bb6753b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_letter', 'raw_news_ids')
    op.add_column('news_raw', sa.Column('news_letter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news_raw', 'news_letter', ['news_letter_id'], ['news_letter_id'])
    op.drop_column('news_raw', 'used_check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_raw', sa.Column('used_check', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news_raw', type_='foreignkey')
    op.drop_column('news_raw', 'news_letter_id')
    op.add_column('news_letter', sa.Column('raw_news_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
